# Generated by Django 4.0.4 on 2022-05-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_author_alter_post_created_date_alter_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
